services:
  backend:
    image: aditya280102/csp-backend:latest
    container_name: csp_backend
    build:
      dockerfile: ./Backend/Dockerfile_backend
      context: ./Backend
    ports: "8081:8081"
    restart: unless-stopped
  
  fronted:
    image: aditya280102/csp-backend:latest
    container_name: csp_frontend
    build:
      context: ./Frontend
      dockerfile: ./Frontend/Dockerfile_frontend
    ports: "3000:3000"
    restart: unless-stopped
    